{% set name = "opentelemetry-instrumentation-langchain" %}
{% set version = "0.49.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 51dbaa023b57040b4105fab4a17ae08bbc4f85d8acbd421e4784ed3f56bf6bfe

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
    - poetry-core
  run:
    - python
    - opentelemetry-api >=1.38.0,<2.0.0
    - opentelemetry-instrumentation >=0.59b0
    - opentelemetry-semantic-conventions >=0.59b0
    - opentelemetry-semantic-conventions-ai >=0.4.13,<0.5
  run_constrained:
    - opentelemetry-sdk >=1.38.0,<2.0.0
    - langchain >=0.3.15,<0.4.0
    - langchain-community >=0.3.3,<0.4.0
    - langchain-anthropic >=0.3.13,<0.4.0
    - langchain-aws >=0.2.11,<0.3.0
    - langchain-openai >=0.3.1,<0.4.0
    - langchain-cohere >=0.3.1,<0.4.0
    - langchain-huggingface >=0.1.2,<0.2.0
    - langchainhub >=0.1.21,<0.2.0
    - langgraph >=0.4,<0.5

test:
  imports:
    - opentelemetry.instrumentation.langchain
  commands:
    - pip check
  requires:
    - pip
    - langchain >=0.3.15,<0.4.0

about:
  home: https://www.traceloop.com/openllmetry
  summary: OpenTelemetry Langchain instrumentation
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: This library allows tracing complete LLM applications built with Langchain.
  dev_url: https://github.com/traceloop/openllmetry
  doc_url: https://www.traceloop.com/docs/openllmetry/introduction

extra:
  recipe-maintainers:
    - timkpaine
  skip-lints:
    - invalid_url
