{% set name = "opentelemetry-instrumentation-langchain" %}
{% set version = "0.57.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: d2cd2f4e3f4c306fb6f2a7275e8acc69fc683809e95347d599b9faf746ac287c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<310]

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - opentelemetry-api >=1.38.0,<2.0.0
    - opentelemetry-instrumentation >=0.59b0
    - opentelemetry-semantic-conventions >=0.59b0
    - opentelemetry-semantic-conventions-ai >=0.5.1,<0.6.0

test:
  imports:
    - opentelemetry.instrumentation.langchain
  commands:
    - pip check
  requires:
    - pip
    - langchain >=1.0.0,<2.0.0

about:
  home: https://www.traceloop.com/openllmetry
  summary: OpenTelemetry Langchain instrumentation
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: This library allows tracing complete LLM applications built with Langchain.
  dev_url: https://github.com/traceloop/openllmetry
  doc_url: https://www.traceloop.com/docs/openllmetry/introduction

extra:
  recipe-maintainers:
    - timkpaine
  skip-lints:
    - reachable_url
